client/src/language/middlewareHover.ts
integration-tests/project-folder/sources/meta-fixtures/hover.bb
integration-tests/src/tests/hover.test.ts

See previous discussion: https://github.com/savoirfairelinux/vscode-bitbake/pull/98

Fix: Hover for Python functions that are Yocto tasks

---

server/src/__tests__/definition.test.ts
server/src/__tests__/fixtures/directive.bb
server/src/connectionHandlers/onDefinition.ts
server/src/tree-sitter/analyzer.ts

Words in the string content are extracted when they are recipe names. Definitions are then created according to these extracted symbols.
e.g. `efivar`, `popt` and `git` in the following screenshots:
Extra definitions are also provided when they have appends (based on bitbake scan results)

Feat: Go to definition for symbols in string content using tree-sitter

---

client/src/extension.ts
server/src/server.ts

The extension started scanning twice at startup. It turns out this was because the extension was sending a rescan request when the python embedded settings where updated. This was fixed by only sending a rescan request when the bitbake settings are changed.

Fix: Only rescan when bitbake settings are changed

---

client/src/extension.ts
client/src/ui/BitbakeCommands.ts

If we set the python extraPaths to the expanded `$pathToBitbakeFolder+'/lib'`, it will
result in an absolute path, i.e.
``` json
"python.autoComplete.extraPaths": [
"/home/patrick/git/<workspace>/poky/bitbake/lib"
],
```
Settings with such an absolute path cannot be version controlled.
Instead, use the path before it is expanded and still contains the
`$workspaceFolder` variable. Then, the written settings look like this:
``` json
"python.autoComplete.extraPaths": [
"${workspaceFolder}/poky/bitbake/lib"
],
```
This is more portable and can be tracked via git.
I tested the change by checking the hover info on some `bb.<func>()` calls, and can confirm the Python extension uses uses the configured extraPaths.
Also fix a small typo that caught my eye. :)

Fix: use unexpanded workspaceFolder var for python extraPaths

---

client/src/language/languageClient.ts

The default behavior of vscode is to save all open editors when a task is run. We currently run the parsing task for any bitbake file save. This means that if you have multiple bitbake files open, all of them will be saved when any one of them is saved which is not the desired behavior.
This patch temporarily disables the saveBeforeRun setting when the bitbake/parseAllRecipes request is received.

Fix: Stop saving all open editors when saving a bitbake file

---

client/src/documentLinkProvider.ts
client/src/extension.ts
client/src/lib/src/types/requests.ts
client/src/lib/src/utils/files.ts
client/src/ui/BitbakeCommands.ts
server/src/__tests__/analyzer.test.ts
server/src/__tests__/fixtures/correct.bb
server/src/connectionHandlers/onDefinition.ts
server/src/server.ts
server/src/tree-sitter/analyzer.ts

Use the `documentLinkProvider` to provide the correct links in the string content.

Feat: follow link prefixed with file:// in the string content using documentLinkProvider

---

client/src/driver/BitBakeProjectScanner.ts
client/src/ui/ClientNotificationManager.ts
integration-tests/src/tests/bitbake-commands.test.ts
integration-tests/src/tests/bitbake-parse.test.ts
integration-tests/src/tests/command-wrapper.test.ts

In integration tests in CI, the dialog promise is rejected at random time events. try/catch does not catch the error, it must actually be handled in the promise rejection handler.

Fix: Handle dialog promise rejection

---

server/src/BitBakeDocScanner.ts
server/src/__tests__/fixtures/hover.bb
server/src/__tests__/hover.test.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts

This adds hover for Yocto defined variables in embedded Python. It works with [the functions to access the datastore](https://docs.yoctoproject.org/bitbake/bitbake-user-manual/bitbake-user-manual-metadata.html#functions-for-accessing-datastore-variables)

Feat: Add hover for Yocto defined variables in embedded Python

---

client/syntaxes/bitbake.tmLanguage.json
client/test/grammars/test-cases/bitbake-operator.bb
client/test/grammars/test-cases/variables.bb
server/src/__tests__/fixtures/semanticTokens.bb
server/src/__tests__/semanticTokens.test.ts
server/src/tree-sitter/utils.ts

Bitbake operators in purple

---

server/src/server.ts

Currently, the parsing of recipes will happen in `onDidSave`. 
@idillon-sfl According to https://github.com/yoctoproject/vscode-bitbake/pull/30
If we want to remove any watch events, the embedded part needs to be implemented somewhere else.

No parsing recipes on watch event

---

server/src/__tests__/analyzer.test.ts
server/src/__tests__/fixtures/bbclass/baz.bbclass
server/src/__tests__/fixtures/directive.bb
server/src/__tests__/fixtures/inc/bar.inc
server/src/__tests__/hover.test.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts
server/src/tree-sitter/declarations.ts

This PR adds the comments above the symbols (Variables and functions) defined in the global scope in the hover definition.
**Sample results**:
Show all comments in the current file and included files
The comments are appended at the end
Caveat:
The results won't reflect right after modifications on the comments in the included files because it needs to run `analyze()` to update the values. Currently, it needs additional input to trigger it.
What I have in mind are these two:
1. Somehow trigger the `analyze()` on the current file when the included files are modified.
2. Maintain the references of the comments in the included files so that the current file always gets the updated comments.
Despite the caveat, the feature itself is ready for review.

Feat: Grab comments above global symbols and show them on hover

---

.github/workflows/update-tree-sitter-wasm-file.yml

Update the action to the recommended version according to https://github.com/yoctoproject/vscode-bitbake/security/dependabot/1

Fix workflow vulnerability in tj-actions

---

server/src/__tests__/fixtures/hover.bb
server/src/__tests__/hover.test.ts
server/src/tree-sitter/analyzer.ts

This ensure the description of the second parameter will be showed on the second parameter of `d.renameVar("test", "DESCRIPTION")`. It also ensure it will not be showed on the second parameter of `d.getVar("DESCRIPTION", "DESCRIPTION")`, as it is currently the case on the staging branch.

Feat: Handle hover on second parameter for Python functions accessing the datastore

---

client/src/extension.ts
client/src/language/middlewareDefinition.ts
integration-tests/project-folder/sources/meta-fixtures/definition.bb
integration-tests/src/tests/definition.test.ts
server/src/embedded-languages/python-support.ts

It also improves the handling of bb. For example, the previous version was not able to find any information for bb.utils.

Chore: Add oe to Python path and imports

---

client/package.json
server/src/server.ts

Sample results:
1. ~Moving~ Add an extra add-recipe operation with the plus icon to the title which can make adding recipes easier in case the list gets too long.
~2. Use less ambiguous icons for the `build recipe` and `clean recipe` operations~
Icon references: https://code.visualstudio.com/api/references/icons-in-labels

Update UI item icons

---

client/TROUBLESHOOTING.md
client/src/language/EmbeddedLanguageDocsManager.ts
client/src/language/languageClient.ts
integration-tests/src/tests/diagnostics.test.ts
server/src/server.ts
server/src/tree-sitter/analyzer.ts

This fixes two problems that occurred when many documents were being opened in the editor:
- onDidChangeContent being called non-stop
- failure to programmatically save a document because it is closed
However, there are others problems happening in that situation that could not be solved.
If you reactivate the diagnostics and open a lot of documents (about thirty), the diagnostics start becoming unstable. They start being re-analyzed non-stop,  making them appearing and disappearing, and slowing down everything. For that reason, the diagnostics have been deactivated

Handle problems spamming

---

server/src/__tests__/definition.test.ts
server/src/__tests__/fixtures/directive.bb
server/src/tree-sitter/analyzer.ts

Fixed the regex that caused some package names containing special characters to not get matched.
Example:
`base-files` in:
https://github.com/yoctoproject/poky/blob/master/meta/recipes-extended/bash/bash.inc#L25
`gtk+3` in:
https://github.com/yoctoproject/poky/blob/98c5c96dd3902cdc4a455a9ed46591037ab3f676/meta/recipes-connectivity/avahi/avahi_0.8.bb#L52
`glib-2.0` in:
https://github.com/yoctoproject/poky/blob/98c5c96dd3902cdc4a455a9ed46591037ab3f676/meta/recipes-connectivity/bluez5/bluez5.inc#L9C1-L9C26

Fix some package names can't trigger go-to-definition

---

client/src/language/languageClient.ts
client/src/language/languageConfiguration.ts
client/src/lib/src/utils/regexp.ts

This increase or decrease the indentation in Python as the user types. For example, the indentation will increase if the user presses enter after `if True:`. It will decrease when the user presses enter after `continue`. It will also start a comment on a new line if the user presses enter after `a` into `# a comment` (this one even works into Bash code).
After exploring various solutions that did not work, I decided to simply copy-paste the code from vscode-python. I can't imagine any realistic case where the Python rules would interfere into Bash code. It will give inconsistent indentation in Bash code if the user press enter after writing something such `if:`, but this would be just as invalid bash code with or without indentation anyway.
I've not attempted to add auto-indentation for …

Feat: Improve auto-indentation

---

client/package.json
client/src/ui/BitbakeTaskProvider.ts
integration-tests/project-folder/sources/meta-error/recipes-error/error/compilation-python-function.bb
integration-tests/project-folder/sources/meta-error/recipes-error/error/error.bb
integration-tests/project-folder/sources/meta-error/recipes-error/error/execution-python-function.bb
integration-tests/project-folder/sources/meta-error/recipes-error/error/task-error.bb
integration-tests/project-folder/sources/meta-error/recipes-error/error/unable-to-parse.bb
integration-tests/project-folder/sources/meta-error/recipes-error/error/unparsed-line.bb
integration-tests/project-folder/sources/meta-error/recipes-error/error/variable-error.bb
integration-tests/src/tests/bitbake-parse.test.ts
integration-tests/src/utils/bitbake.ts
server/src/server.ts

Removed `bitbake-generic` since it could cover a wide range of error messages. Precise ones should be used to avoid overlap since they differ in the positions of the line numbers.

Fix some errors not matched by problem matcher

---

client/package.json
client/src/__tests__/unit-tests/driver/bitbake-driver.test.ts
client/src/driver/BitbakeDriver.ts
client/src/driver/BitbakeRecipeScanner.ts
client/src/extension.ts
client/src/language/languageClient.ts
client/src/lib/src/types/notifications.ts
client/src/lib/src/types/requests.ts
client/src/ui/BitbakeCommands.ts
client/src/ui/BitbakeTaskProvider.ts
client/src/ui/BitbakeTerminal.ts
client/src/ui/ClientNotificationManager.ts
server/src/__tests__/analyzer.test.ts
server/src/__tests__/fixtures/declarations.bb
server/src/server.ts
server/src/tree-sitter/analyzer.ts
server/src/tree-sitter/declarations.ts

This PR adds an option in the contextual menu to trigger **bitbake some-recipe -e** in the terminal and ~uses the results to provide more robust information about the environment of the selected recipe such as the complete include history, the current final value for a variable, etc.~ sends the results to the server for further processing.
Edit: This PR only prepares the parsing. 
Edit-2: The actual processing will be in other PRs.
Ticket No. 10429

Send bitbake -e <package> output to the server for further processing

---

client/src/language/middlewareHover.ts
server/src/server.ts

For embedded languages hover, if a third party extension contributed empty hovers, we would return the first result that might be empty, resulting in the interesting hovers from embedded languages extension being lost. We add a find() to filter out empty hovers.

Fix: Handle empty hover middleware forwarding

---

integration-tests/project-folder/sources/meta-fixtures/completion.bb
integration-tests/src/tests/completion.test.ts
server/src/tree-sitter/analyzer.ts

Completion was broken on the last character of Python or Bash blocks.
For example, in the following code, if the cursor was on just after the `h` in `ech`, the user would see "normal" bitbake completion items instead of bash completion items. 
```shell
test() {
ech
}
```
Completion is still not as responsive as we'd like it to be, especially in Python. I am still looking for a solution.

Fix: Completion on last character of embedded language blocks

---

server/src/__tests__/embedded-languages.test.ts
server/src/embedded-languages/bash-support.ts

Before this fix, ShellCheck gives a warning about functions being unreachable when there is an override. It happens because we delete the override part (ex. `:append`) in the embedded language document, so ShellCheck sees the same function.
This PR simply disables that warning.

Fix: Disable ShellCheck rule SC2317

---

client/src/language/languageClient.ts
client/src/language/middlewareHover.ts
client/src/lib/src/BitbakeSettings.ts
integration-tests/project-folder/sources/meta-fixtures/hover.bb
integration-tests/src/tests/hover.test.ts
server/src/embedded-languages/bash-support.ts
server/src/embedded-languages/general-support.ts
server/src/server.ts

This adds hover, completion and diagnotics for the functions defined into `poky/meta/classes-global/logging.bbclass`  and `poky/meta/classes-global/base.bbclass`. It also prevents them from being marked as undefined by the diagnostics tools.
This also reintroduces synchronization for the vscode settings on the language server (onDidChangeConfiguration was not working anymore).

Feat: Add support for embedded bash tools

---

client/src/language/middlewareCompletion.ts
client/src/lib/src/utils/arrays.ts
integration-tests/project-folder/sources/meta-fixtures/completion.bb
integration-tests/src/tests/completion.test.ts
server/src/__tests__/completions.test.ts
server/src/__tests__/fixtures/completion.bb
server/src/connectionHandlers/onCompletion.ts
server/src/tree-sitter/analyzer.ts

This adds completion items for Yocto variables inside Python datastore functions. 
This also add completion items for Yocto tasks inside Python and Shell functions. 
Completion items for variable expansions inside Shell regions is waiting for a fix on tree-sitter-bitbake (see [PR19](https://github.com/amaanq/tree-sitter-bitbake/pull/19))

Feat: Add completion for Yocto defined variables in embedded languages

---

server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts

Fixed the issue that the scan results were lost after changing the documents. I still want the `analyze()` to be called on every keystroke so the document gets the correct tree-sitter parsing right away, so I stored the results of the previous scan and read them on request to fix this. Now only the final values are fixed, the history will be fixed after I refactor it so it becomes part of the `bitbakeSymbolInformation` and I don't have to duplicate the logic.

Fix: scanned results lost on type

---

server/src/__tests__/analyzer.test.ts
server/src/connectionHandlers/onDefinition.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts
server/src/tree-sitter/declarations.ts

The tests related to this refactoring all passed. The only thing I added in the test is the `commentsAbove` field which is initialized every time a `bitbakeSymbolInformation` object is created.
Also fixed the history was lost on type. Now it is computed from the last scan results.
Expected results after triggering the command `scan recipe` from the menu. Typing should not remove or change the results:

Refactor: comment now is part of bitbakeSymbolInformation

---

client/src/language/middlewareHover.ts
client/src/language/utils.ts
integration-tests/project-folder/sources/meta-fixtures/hover.bb
integration-tests/src/tests/hover.test.ts

This fixes the line numbers on hover given by Bash IDE for variable and functions defined on the same file. Previously, it would give the line numbers from the "embedded language document" instead of the actual file.

Fix: Bash IDE line numbers

---

client/src/language/languageClient.ts
server/src/server.ts

I only replaced the command executed on save and made it work on recipe files. The `parseAllRecipe` still runs after the initial project scan on launch. I think we should keep it so we know if there is any errors at the start.

Chore: Replace parseAllRecipe with bitbake -e command on recipe files on save

---

server/src/__tests__/analyzer.test.ts
server/src/__tests__/fixtures/declarations.bb
server/src/connectionHandlers/onDefinition.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts
server/src/tree-sitter/declarations.ts

In the example below, the final values and modification history should still apply to the variable `FILES`:
This requires the values of the variables in the variable expansion to be resolved first.

Fix: final values should work on variables with variable expansion in the overrides

---

client/src/language/languageClient.ts

This has been removed on commit 21fae6a8b1ce8bf48926890515301c7eab87229a. However there is still a call to it in server/src/server.ts and it throws the following error: `ResponseError: Unhandled method bitbake/parseAllRecipes`.

Fix: Handle 'bitbake/parseAllRecipes' on client side

---

server/src/__tests__/analyzer.test.ts
server/src/__tests__/definition.test.ts
server/src/__tests__/fixtures/directive.bb
server/src/connectionHandlers/onDefinition.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts

The directive paths will be resolved first before they are used to create the definition item.
Working example:
Note that even if the resolved path is obtained, if the results from the project scan don't have the corresponding file, no definition will be provided.
Ticket: 14024

Feat: Provide go-to-definition for include path that contain ${} syntax

---

client/src/ui/BitbakeCommands.ts
client/src/ui/BitbakeRecipesView.ts
client/src/ui/DevtoolWorkspacesView.ts

When opening a fresh eSDK, there is no devtool workspace open yet. The previous logic had to wait before resolving. This made the "New devtool workspace" missing from the tree view.

Fix: Resolve devtool workspace for new eSDK projects

---

server/src/connectionHandlers/onDefinition.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts

The symbols that can't match the exact result from the scan can now fall back to the one with no overrides.
In this example, the `SRC_URI:libc-musl` will take the final value of `SRC_URI` since there isn't any for the exact symbol.

Chore: Match exact symbol or symbol without override as fallback

---

client/src/lib/src/utils/OutputLogger.ts
server/src/server.ts

1. Prepend timestamp and level to the log messages.

Chore: Add timestamp and log level to log messages

---

scripts/update-tree-sitter-wasm.sh

The repo has been moved to different account, hence the API URI changed.
https://github.com/tree-sitter-grammars/tree-sitter-bitbake
How to verify:
Run the script in the project root and it should update the `parser.info` with the latest commit of the `tree-sitter-bitbake` and the latest version of [tree-sitter-cli](https://github.com/tree-sitter/tree-sitter)
Example:
Let the bot create a new PR for the update next time for validation.

Chore: Update script for tree-sitter

---

client/src/language/languageClient.ts
client/src/ui/BitbakeCommands.ts

We want to avoid saving all files when running the parsing or recipe scan tasks. Otherwise, all documents get saved and the commands fire again. This was done at the server level on save but missed the commands started from the pallet or context menu.

Fix: Also disable saving on parse from the commands

---

server/src/__tests__/analyzer.test.ts
server/src/__tests__/definition.test.ts
server/src/__tests__/fixtures/correct.bb
server/src/__tests__/hover.test.ts
server/src/tree-sitter/analyzer.ts
server/src/tree-sitter/declarations.ts

Resolve overrides that are partially `${}` and provide final values on hover accordingly:
Result:
File in the example:
`poky/meta/recipes-kernel/dtc/dtc_1.7.0.bb` L: `31`
Ticket: 14140

Feat: Resolve partial variable expansion in overrides

---

server/src/__tests__/definition.test.ts
server/src/__tests__/fixtures/directive.bb
server/src/connectionHandlers/onDefinition.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts

If there is a `conf` file for the override, `go to definition` should be provided:
Ticket: 14091

Feat: go to definition for overrides

---

__mocks__/vscode.ts
client/package.json
client/src/__tests__/unit-tests/bitbake-workspace.test.ts
client/src/__tests__/unit-tests/ui/bitbake-recipes-view.test.ts
client/src/ui/BitbakeCommands.ts
client/src/ui/BitbakeRecipesView.ts
client/src/ui/BitbakeWorkspace.ts

The quick pick allows to search among all detected recipes. We resort to the input box only if no recipes have been found yet.
Fixes #10 
A new button allows clearing the bitbake recipes view

Recipe list improvements

---

client/src/extension.ts
client/src/lib/src/types/notifications.ts
server/src/connectionHandlers/onHover.ts
server/src/server.ts
server/src/tree-sitter/analyzer.ts

Note that vscode only provides the `visibleEditors` instead of all the opened editors. If a file related to a recipe is still opened but not visible in the current window, it loses its scan results as well.

Misc: Move final values above the definition in the hover; Remove scan results on closing all files related to a recipe

---

server/src/__tests__/definition.test.ts
server/src/__tests__/fixtures/inc/bar.inc
server/src/tree-sitter/analyzer.ts

This PR gives the extra definitions for functions using the scan results.
Dummy example:
In the example above, the function in the `inc` file shows the definitions from the recipe `bb` file which includes this `inc` file.
What is like in the scan results:
Ticket: 14072

Feat: extra definition for functions using scan results

---

client/src/language/codeActionProvider.ts
client/src/language/languageClient.ts
client/src/language/utils.ts
integration-tests/project-folder/sources/meta-fixtures/code-actions.bb
integration-tests/src/tests/code-actions.test.ts

This proposes vscode-python's quick fixes when Python imports are missing.
Final result is
``` python
python() {
import random
random()
}
```
It is not very sophisticated. The new import will always appear on the line just before. Furthermore, if it imports two objects from the same module, it will create two lines instead of putting both imports on the same line (it will never do `from random import random, choice`.
For now it is more a proof a concept, in order to decide if we want to put more efforts on quick fixes.

Feat: Handle Quick Fix python.addImport

---

server/src/semanticTokens.ts
server/src/tree-sitter/utils.ts

Ticket: 14170
Was:
append/prepend/remove were not in the color of keywords
Now:

Fix: Incorrect highlighting on bitbake operators after function identifiers

---

client/TROUBLESHOOTING.md
client/src/language/EmbeddedLanguageDocsManager.ts
client/src/language/codeActionProvider.ts
client/src/language/diagnosticsSupport.ts
client/src/language/languageClient.ts
client/src/language/middlewareCompletion.ts
client/src/language/middlewareDefinition.ts
client/src/language/middlewareHover.ts
client/src/lib/src/utils/hash.ts

These are a bunch of small refactors I've wanted to do for a while for the embedded language documents
- Remove functionalities that are not used anymore since we deactivated the "watch" files
- Use hashes instead of uuids for filenames. It simplifies debugging, since both embedded language documents have the same name, and these names never change. It also reduces the speed the embedded language documents folder will grow. 
- Avoid updating Bash and Python diagnostics at the same time. Prior to these changes, new Python diagnostics would always update both Python and Bash diagnostics, and vice versa.

Refactor: Simplify embedded language documents

---

client/src/ui/BitbakeCommands.ts

This is a small fix for a regression. The recipe wasn't automatically opened anymore.

Fix: Update regex for devtool update-recipe for node-pty

---

integration-tests/src/tests/definition.test.ts

According to the documentation, the `vscode.executeDefinitionProvider` command returns an array of `Location` or `LocationLink` objects. In the case a `LocationLink` object is returned, the test probably waited infinitely.

Fix: Random definitions integration test failure

---

client/package.json
client/src/driver/BitBakeProjectScanner.ts
client/src/extension.ts

Ticket: 14138
The project scanner runs `bitbake-layers show-recipes` to get the recipe names and the corresponding layer and version. But the path for the recipes can only be returned when the `-f` flag is passed because CLI doesn't support returning everything in one go.
Output of `bitbake-layers show-recipes`:
Output of `bitbake-layers show-recipes -f`:
So we execute the command twice to get the recipes and their matching path. However, some of the recipe names can have random strings at the end which can't be used easily to compare with the path.
Example:
```
name: gcc-source-13.2.0
path: /home/projects/poky/meta/recipes-devtools/gcc/gcc-source_13.2.bb
```
Before, we ran `bitbake-layers show-recipes -f <recipe-name>` to get the target path for a specific know recipe, but this is slow …

Fix recipe scan in project scanner

---

client/src/__tests__/unit-tests/language/EmbeddedLanguageDocsManager.test.ts
client/src/extension.ts
client/src/language/EmbeddedLanguageDocsManager.ts
client/src/language/languageClient.ts
client/src/lib/src/utils/OutputLogger.ts
server/src/__tests__/analyzer.test.ts
server/src/__tests__/completions.test.ts

This deletes the folder containing "embedded language documents" when the extension is deactivated. It ensures that folder won't grow infinitely.
According to my experiments, when testing this change in "Extension Development Host", the window has to be closed with the "x" button in order to have "deactivate" to be called. Clicking on the red square stop button won't do.
Unfortunately, there seems to be no way to call "deactivate" from the integration test environment.

Clean up embedded language documents on deactivate

---

.vscode/launch.json
client/package.json
client/src/extension-web.ts
client/src/extension.ts

Ticket: 13882
According to the docs: https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-main-file
~The web extension needs to be packaged into a single file because the `import/require` statements are not allowed. The docs recommend using the webpack.~
~Issues:~
~1. Dynamic import of node-pty in `client/src/utils/ProcessUtils.ts`~
~2. Webpack Can't resolve modules from node such as `fs`, `path` etc. Need to have substitutes.~
~3. Need to handle various scenarios when the extensions are absent when we remove them from the dependencies.~
This PR will only bring basic highlighting to the web.
To debug:
Launch the web client through the debug panel and bitbake files should have the syntax highlighting that `tmLanguage.json` provides.

Feat: Web support with only highlighting

---

client/src/ui/BitbakeTerminal.ts

It is possible to stop a non interactive bitbake terminal by closing it.
Users may find it more intuitive to press Ctrl+C. We disable typing in those terminals but we could handle Ctrl+C specifically and call the appropriate kill function.

Feat: Allow to kill bitbake terminals with Ctrl+C

---

client/src/ui/BitbakeConfigPicker.ts

A very trivial improvment to the UI. Adds a hover description on the bottom right config picker

UI: Add tooltip to config picker

---

client/package.json
client/src/__tests__/unit-tests/driver/scanner.test.ts
client/src/__tests__/utils/bitbake.ts
client/src/driver/BitBakeProjectScanner.ts
client/src/extension.ts
client/src/lib/src/utils/files.ts
integration-tests/project-folder/sources/meta-fixtures-versions/conf/layer.conf
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_%.bbappend
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.1.0.bb
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.1.0.bbappend
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.2.0.bb
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.2.0.bbappend
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.3.0.bb
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.3.0.bbappend

When multiple version of a recipe existed, PREFERRED_VERSION wasn't necesseraly the one showed in the bitbake recipe view

Detect PREFERRED_VERSION and optimize recipe paths scan

---

client/package.json

Ticket: 14106
Before, the extension will be activated whenever a file with languageId bitbake is opened and focused. Now it activates when vscode finds a bblayers.conf in the workspace.

Activate the extension if the workspace contains a bblayers.conf

---

client/package.json

We need the highlighting and language features there. Unfortuanetly this implicitely adds them as activation events but VSCode has no way of preventing that.

Fix: Restore .inc and .conf file extensions

---

client/src/language/codeActionProvider.ts
client/src/language/diagnosticsSupport.ts
client/src/language/languageClient.ts
client/src/language/middlewareCompletion.ts
client/src/language/middlewareDefinition.ts
client/src/language/middlewareHover.ts
client/src/language/middlewareReferences.ts
client/src/language/utils.ts
client/src/language/utils/definitions.ts
client/src/language/utils/embeddedLanguagesUtils.ts
client/src/language/utils/textDocumentUtils.ts
integration-tests/project-folder/sources/meta-fixtures/references.bb
integration-tests/src/tests/code-actions.test.ts
integration-tests/src/tests/definition.test.ts
integration-tests/src/tests/references.test.ts
integration-tests/src/utils/vscode-tools.ts

This adds references into embedded languages regions
Contrary to definitions, it does not handle `d` and `e`. I am not sure how it could be done.

Feature: Forward references for embedded languages

---

client/syntaxes/bitbake.tmLanguage.json
client/test/grammars/snaps/keywords.bb
client/test/grammars/test-cases/keywords.bb

Fix: incorrect highlighting on keyword 'python'

---

integration-tests/src/tests/definition.test.ts

We already have a unit test for this in
server/src/__tests__/definition.test.ts
This test randomly got stuck in CI.

Fix: Remove definition inherit integration test

---

client/src/driver/BitbakeRecipeScanner.ts
client/src/extension.ts
client/src/language/RequestManager.ts
client/src/language/diagnosticsSupport.ts
client/src/language/languageClient.ts
client/src/lib/src/types/requests.ts
integration-tests/src/tests/diagnostics.test.ts
server/src/server.ts

This uses the result of the scan in order to remove Shellcheck warnings of variables that are actually available
Before the scan of the recipe:
After the scan of the recipe:

Chore: Use scan result to validate diagnostics of undefined variables

---

client/TROUBLESHOOTING.md
client/package.json
client/src/extension.ts
client/src/language/EmbeddedLanguageDocsManager.ts

This adds a setting to disable the generation of "embedded language files". 
Unfortunately, I realized it won't be possible to disable only the diagnostics. If it was, we would not have these unwanted diagnostics polluting the "PROBLEMS" tab.

Feat: Add 'bitbake.disableEmbeddedLanguagesFiles' setting

---

client/src/language/middlewareReferences.ts
integration-tests/project-folder/sources/meta-fixtures/references.bb
integration-tests/src/tests/references.test.ts

We have the integration tests faililng since the merge of the new tree-sitter-bitbake version:
https://github.com/yoctoproject/vscode-bitbake/actions/runs/8284971253/job/22671672578?pr=173#step:8:22130
https://github.com/yoctoproject/vscode-bitbake/actions/runs/8279689831/job/22654612415#step:8:22599
The issue is because the variables expansions inside bash regions are now included into the references by the onReference handler (see [this line](https://github.com/yoctoproject/vscode-bitbake/blob/staging/server/src/connectionHandlers/onReference.ts#L33C21-L33C48)).
Instead of trying to fix the issue directly on that line, I decided to merge the results together. It has for benefit that the references outside of the bash region are now also included in the references list. I added a test …

Fix: Variable expansion references inside Shell region

---

client/src/driver/BitBakeProjectScanner.ts
client/src/extension.ts

Save the last scan results in the workspace state to reuse it and skip the scan in the next startup. 
Ticket: 14207

Cache last scan results

---

client/README.md
client/package.json
client/src/driver/BitbakeDriver.ts
client/src/ui/BitbakeCommands.ts
client/src/ui/BitbakeStatusBar.ts
client/src/ui/BitbakeTerminal.ts

Ticket: 13369
1. Added a command to start the toaster and redirect the users to the browser with the toaster UI. This command is accessible through the main context menu 
2. Added a command to stop the toaster by spawning a process that will run the command `source toaster stop`

Feat: Start toaster through context menu

---

client/src/ui/BitbakeRecipesView.ts

It makes it more convenient to browse the view if they are sorted.

Feat: Sort recipes in the tree view

---

.github/workflows/main.yml

This PR updates the following actions to the versions that support node20. [Reason](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
`actions/checkout@v4`: [changelog](https://github.com/actions/checkout/releases/tag/v4.0.0)
`actions/setup-node@v4`: [changelog](https://github.com/actions/setup-node/releases/tag/v4.0.0)
These two didn't mention node20 in the change log specifically:
`actions/upload-artifact@v4`: [PR](https://github.com/actions/upload-artifact/issues/444)
`actions/download-artifact@v4`: [action.yml](https://github.com/actions/download-artifact/blob/c850b930e6ba138125429b7e5c93fc707a7f8427/action.yml#L39)
Ticket: 14334

Use actions that run on node20

---

server/.npmignore
server/package-lock.json
server/package.json

Fixes language server packaging change in 40cef6296e09bb0d0ff6eb41aef41dde3c56bea0
The compilation path has been updated but not the bin path in the package.json. This broke the VIM integration.

Fix: Update server bin in package

---

.github/workflows/update-ref.yml
.github/workflows/update-tree-sitter-wasm-file.yml

To prevent PR like https://github.com/yoctoproject/vscode-bitbake/pull/210 from being created where the target branch should be `staging` instead of the `main` which is the default branch.

Specify target branch for the auto PR

---

client/src/ui/BitbakeCommands.ts
client/src/ui/BitbakeStatusBar.ts
package.json

This adds two commands. One to generate the dependency graph, and the other to examine the dependency graph with taskexp.
In fact, both are independent commands that will generate the dependency graph. I have in mind the first one could be handful if the user has installed the [Yocto Project Dependency Visualizer](https://marketplace.visualstudio.com/items?itemName=MLinha.yocto-project-dependency-visualizer) extension, which won't generate the .dot file by itself, or eventually an other similar extension.
Note it is not possible to run an other BitBake command while taskexp is launched.

Feature: Add commands to generate and examine the dependency graph

---

TROUBLESHOOTING.md
client/src/extension.ts
package.json

The "interfering settings" are moved to "configurationDefaults" so they can be deactivated without having to modify the user's settings.json file.

Refactor: Use 'configurationDefaults' instead of 'disableInteferingSettings'

---

client/src/language/languageClient.ts
client/src/language/middlewareRename.ts
integration-tests/project-folder/sources/meta-fixtures/rename.bb
integration-tests/src/tests/rename.test.ts

This adds rename on Python and Shell local symbols.
Example:
```
foo_global='foo'
python() {
foo_local_python='foo'
print(foo_local_python)
d.getVar('foo_global')
}
do_stuff() {
echo "${foo_global}"
local foo='foo_local_shell'
echo "$foo_local_shell"
}
```
Here it adds rename to `foo_local_python` and `foo_local_shell`. `foo_global` is already handled, and #215 fixes a couple of things on it.

Chore: Add rename to local python and shell symbols

---

.github/workflows/main.yml
.github/workflows/update-ref.yml
.github/workflows/update-tree-sitter-bash-wasm-file.yml
.github/workflows/update-tree-sitter-bitbake-wasm-file.yml
.github/workflows/update-tree-sitter-wasm-file.yml
client/src/__tests__/unit-tests/driver/scanner.test.ts
client/src/__tests__/utils/bitbake.ts
client/src/language/languageClient.ts
integration-tests/project-folder/.vscode/settings.json
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_%.bbappend
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.1.0.bb
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.1.0.bbappend
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.2.0.bb
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.2.0.bbappend
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.3.0.bb
integration-tests/project-folder/sources/meta-fixtures-versions/recipes-fixtures/fixture-version/fixture-version_0.3.0.bbappend
integration-tests/src/tests/bitbake-commands.test.ts
integration-tests/src/tests/bitbake-parse.test.ts
integration-tests/src/utils/bitbake.ts
scripts/fetch-poky.sh

This PR improves the workflow display and optimizes runtime with caches

Ci enhancements

---

integration-tests/project-folder/sources/meta-fixtures/rename.bb
integration-tests/src/tests/rename.test.ts
server/src/__tests__/completions.test.ts
server/src/__tests__/fixtures/completion.bb
server/src/connectionHandlers/onCompletion.ts
server/src/connectionHandlers/onHover.ts
server/src/tree-sitter/analyzer.ts
server/src/tree-sitter/declarations.ts

Still breaking down #215 in smaller parts.
This actually adds support for simple variable expansions on hover, references, definitions, rename and completion. However, I propose the reduce the scope of this PR to completion in order to reduce things to review. #215 has proper tests for the other functionalities.
This also adds some modifications to the rename integration test, since the changes would broke it for reasons that are not well understood.

Feat: Handle completion on bash simple variable expansion

---

server/src/__tests__/fixtures/semanticTokens.bb
server/src/__tests__/semanticTokens.test.ts
server/src/semanticTokens.ts
server/src/tree-sitter/analyzer.ts

In the following example, it adds highlighting to the command `do_stuff` and the variable `$FOO`, which were not handled before.

Chore: Add semantic highlighting to bash variables and commands

---

client/src/language/RequestManager.ts
client/src/language/diagnosticsSupport.ts
client/src/language/languageClient.ts
client/src/language/middlewareDefinition.ts
client/src/language/middlewareReferences.ts
client/src/lib/src/types/requests.ts
integration-tests/src/tests/rename.test.ts
server/src/server.ts
server/src/tree-sitter/analyzer.ts

This adds "definition" functionality to variables that are required, inherited or included into Bash or Python regions. It also filter out Pylance's `reportUndefinedVariable` when the variable is actually defined. It even removes the requirement to make a new scan for filtering out shellchecks `SC2154` diagnostics when the variable actually exist.
Lets take examples from the file `meta/recipes-core/busybox/busybox.inc` in Poky. After, a scan, `find_cfgs` (python region) won't appear anymore as undefined, and clicking on it will bring to its definition in `meta/classes-recipe/cml1.bbclass`. `cml1_do_configure` (shell region) will also bring to its definition when clicked.

Feat: Import require/inherit in Bash and Python context

---

.github/dependabot.yml

With this file, Github will periodically check for version updates for the npm packages. **The `Code security and analysis` -> `Dependabot on Actions runners` setting must be enabled for this behaviour to take effect.**

Chore: Add dependabot.yml for auto checks for dependency updates

---

client/src/language/middlewareReferences.ts
integration-tests/project-folder/sources/meta-fixtures/references.bb
integration-tests/src/tests/references.test.ts
server/src/connectionHandlers/onReference.ts
server/src/tree-sitter/analyzer.ts

Still merging #215 in smaller parts. 
In the following example, both FOO will give the same references.
```
FOO="bar"
python() {
d.getVar("FOO")
}
```

Fix: Python datastore variables on references

---

server/.npmignore

In order for the standalone server to work on neoVim, it needs this dependency.

Fix: Update server .npmignore to include tree-sitter-bash.wasm

---

client/src/language/middlewareDefinition.ts
server/src/__tests__/embedded-languages.test.ts
server/src/embedded-languages/bash-support.ts
server/src/embedded-languages/python-support.ts

Only commit still relevant on #237 .
This simply adds the uri of the original document as a comment on the embedded language document in order to ease debugging.

Chore: Add comment with original uri on embedded language documents

---

client/src/language/languageClient.ts

The synchronize option is marked as deprecated but what we did to sync the settings was not a good practice either. The recommended pull-model for configurations is demonstrated [here](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#explaining-the-language-server). However, this model doesn't really fit our case as the logging level needs an immediate update but others can be fetched when needed.
One of the advantages of using the pull-model is it can specify the scope (user/workspace/workspaceFolder) of the configurations before fetching.

Use synchronize option to sync settings

---

server/src/connectionHandlers/onCompletion.ts
server/src/connectionHandlers/onHover.ts
server/src/embedded-languages/general-support.ts
server/src/semanticTokens.ts
server/src/tree-sitter/analyzer.ts

I noticed pythonDatastoreVariableSymbols would give inconsistent results when the document is edited.
Steps to reproduce:
1. Create the following document:
``` bitbake
python() {
d.getVar('DESCRIPTION')
}
```
3. Restart VS Code (just making sure to have a clean state) and open the document.
4. Try to hover `DESCRIPTION`. It works.
5. Try to rename `DESCRIPTION`. It works.
6. Change the quotes:
``` bitbake
python() {
d.getVar("DESCRIPTION")
}
```
7. Try to hover `DESCRIPTION`. It still works.
8. Try to rename `DESCRIPTION`: `The element can't be renamed` (???)
9. Save the document and restart VS Code.
10. Try to rename `DESCRIPTION`: It works.
~~Not sure why this happens (`bitBakeNodeAtPoint` gives a different result after the edition), but here's a fix.~~
Problem has been understood: …

Fix: pythonDatastoreVariableSymbols sometimes misses variables

---

integration-tests/src/tests/references.test.ts
server/src/connectionHandlers/onCompletion.ts
server/src/connectionHandlers/onHover.ts
server/src/embedded-languages/general-support.ts
server/src/tree-sitter/analyzer.ts

Some `nodeAtPoint` was forgotten in PR #283 . `isPythonDatastoreVariable` also calls `isInsidePythonRegion`

Chore: analyzer.isInsidePythonRegion takes a node for parameter

---

server/src/semanticTokens.ts
server/src/tree-sitter/analyzer.ts
server/tree-sitter-bitbake.info

This fixes nested variable expansions in shell regions
```
cmake_runcmake_build() {
bbnote ${DESTDIR:+DESTDIR=${DESTDIR} }${CMAKE_VERBOSE} cmake --build '${B}' "$@" -- ${EXTRA_OECMAKE_BUILD}
eval ${DESTDIR:+DESTDIR=${DESTDIR} }${CMAKE_VERBOSE} cmake --build '${B}' "$@" -- ${EXTRA_OECMAKE_BUILD}
}
```
Here's a test I added: https://github.com/idillon-sfl/tree-sitter-bitbake/blob/821169a172bfe3c7125927ca151e299a1f43759b/test/corpus/shell.txt#L45
Note the new version of tree-sitter-bitbake does not handle shell variable expansions anymore. It was a lot of trouble, and we now use tree-sitter-bash instead for those.

Chore: Update tree-sitter-bitbake

---

package.json

The script fetch:spdx-licenses is now a mandatory step to build the extension.

Chore: Update script

---

.github/workflows/update-tree-sitter-parser-info-file.yml
README-DEVELOPER.md
scripts/update-tree-sitter-bash-wasm.sh
scripts/update-tree-sitter-bash.sh
scripts/update-tree-sitter-bitbake-wasm.sh
scripts/update-tree-sitter-bitbake.sh
scripts/update-tree-sitter.sh

We no longer track and update the wasm files in our project, related terms on wasm should be updated.
This should solve the issue: https://github.com/yoctoproject/vscode-bitbake/actions/runs/10162417152/job/28103046768#step:7:65
Ticket: 15307

Chore: Update CI, scripts and README on wasm

---

scripts/update-ref.sh

Use `git ls-remote` command to fetch refs or tags without cloning the projects first. This script now only takes a few seconds to complete.

Chore: Optimize update-ref script

---

client/src/driver/BitBakeProjectScanner.ts

The current master branch also outputs the .bb location in the devtool status output. It broke our parsing which could not detect the workspaces.
The regex was updated to optionally match the .bb location. But we don't capture it since we always run a complete scan in the end. This could be way for future optimizations.

Fix: Adapt devtool status parsing for new Yocto releases

---

client/src/__tests__/unit-tests/driver/eSDKMode.test.ts
client/src/driver/BitbakeDriver.ts

If the user configures a faulty working directory, the error message was not very clear. This very simple check will show a more clear message early on.
Closes #306

UI: Add a sanity check for the working directory

---

.github/workflows/main.yml

With the fetch script refactoring, we had a regression in the node package of the CI wich missed these resources.
Fixes #308

Fix: Fetch WASM and SPDX licenses in NPM package in CI

---

.github/workflows/update-ref.yml

> This PR should wait for #293 
The step that is creating the pull request was adding only 2 files but the script might update more than that. Hence, the `add-path` is removed so all the changed files will be added to the git staging for commit.

Chore: Update CI

---

client/src/driver/BitBakeProjectScanner.ts

This is not a regular bitbake command, which have a default timeout that's 300s. This command should be faster, so 20s is enough.
Related to #312

Fix: Add a smaller timeout for container inode scan

---

client/src/driver/BitBakeProjectScanner.ts
client/src/driver/BitbakeDriver.ts
client/src/ui/BitbakeCommands.ts
client/src/ui/BitbakeTerminalProfile.ts

In the specific case of the BitbakeTerminalProfile, the environment used was the one defined in the global settings. It did not take into account the ones defined in the build configurations if defined.

Fix: Pass buildConfigurations environment to terminal profile

---

client/src/ui/BitbakeCommands.ts

Two months ago, a commit was introduced that adds tasks with special characters which broke our JSON parsing.
Since this variable is not extended, we might miss some tasks, but at least we keep providing the feature. I could not identify a replacement variable that would contained the expanded list of tasks.
We would need to run a `bitbake list-tasks` but it would be slower.

Fix: task_deps parsing on newer Yocto versions

---

client/src/__tests__/unit-tests/driver/scanner.test.ts
client/src/__tests__/unit-tests/ui/bitbake-recipes-view.test.ts
client/src/driver/BitBakeProjectScanner.ts
client/src/extension.ts
client/src/lib/src/types/BitbakeScanResult.ts
client/src/ui/BitbakeRecipesView.ts

View skipped recipes

---

client/src/driver/BitbakeDriver.ts
client/src/ui/BitbakeTerminalProfile.ts
package.json

Should improve issues like #350

Ssh agent forward shellenv

---

client/syntaxes/bitbake.tmLanguage.json
client/test/grammars/snaps/keywords.bb
client/test/grammars/test-cases/functions.bb
client/test/grammars/test-cases/keywords.bb

Fix: 'python' highlighting when not a keyword

---

client/images/yocto-file-icon.svg

The dot in the Yocto logo would not show in such small dimensions. The file icon looked off compared to other icons.
Old look
New look

UI: re-align file icon

---

client/src/__tests__/unit-tests/driver/scanner.test.ts
client/src/__tests__/unit-tests/ui/bitbake-commands.test.ts
client/src/driver/BitBakeProjectScanner.ts
client/src/extension.ts
client/src/ui/BitbakeCommands.ts
client/src/ui/BitbakeConfigPicker.ts
client/src/ui/BitbakeRecipesView.ts
client/src/ui/DevtoolWorkspacesView.ts
package.json

Scan per build config
